# Identifiant unique du projet sur SonarCloud
sonar.projectKey=rivohery_micro-finance
sonar.organization=rivohery
sonar.projectName=micro-finance
sonar.projectVersion=1.0.0
sonar.sources=src/main/java
sonar.tests=src/test/java


# Tests
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Dossiers à exclure (ne pas analyser)
#sonar.exclusions=**/model/**, **/dto/**, **/config/**, **/exception/**

# Qualité
#sonar.java.spotbugs.reportPaths=target/spotbugsXml.xml
#sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

# Langue
#sonar.language=java