spring:
  datasource:
    # Si la variable DB_NAME n'existe pas, Spring utilisera "db_micro_finance" par défaut
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_micro_finance}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:rivohery}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev



